name: Playwright Tests
on:
  push:
    branches: [ main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Playwright
      uses: actions/checkout@v4

    - name: Checkout Repo
      uses: action/checkout@master
      with:
        repository: CodyHodge/AU-CI-Test 
        path: AU-CI-Test 

   - name: Use node 
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Axe
      run: npm install @axe-core/playwright
    - name: Install HTML Reporter
      run:  npm install axe-html-reporter
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: accessibilityReport.html
        path: axe-results/
        retention-days: 30
